### ISSUE TITLE
Clarify stack safety

### ISSUE THREAD

**Issue by ceedubs** [travisbrown/macavity#4]
The README currently says this:

> The StateT implementation provided by this project is mostly source-compatible with Cats's, but it relies on the context it transforms for stack safety

Could you please expand upon what the expected level of stack safety is?

I'd like for the cats implementation of `StateT` to be more efficient, but the reason we have the extra `F` context in the `run` value is indeed because of stack safety. It forces computations to be lifted into the `F` context so that trampolining can be applied.

For example with cats:

``` scala
import cats._, data._, implicits._
(0 to 10000).toList.traverseU(i => StateT[Eval, Int, Int](s => Later((s + 1, i)))).runS(0).value
// res0: Int = 10001
```

With macavity:

``` scala
import cats._, implicits._, io.macavity.data.StateT
(0 to 10000).toList.traverseU(i => StateT[Eval, Int, Int](s => Later((s + 1, i)))).runS(0).value
// java.lang.StackOverflowError
```

I'd love to find out that there's a better solution to this problem.

**Comment by travisbrown** [comment]
Ugh, you're right—I spoke too soon (that's what I get for talking about a project before I write tests for it.). I'll update this afternoon.

**Comment by travisbrown** [comment]
Okay, I've built in type safety in #6, and I think it works.

@vkostyukov, to answer your question this morning: with stack safety and real benchmarks that actually do something, we're down to 2.1x throughput (from my meaningless 2.7x yesterday).

**Comment by vkostyukov** [comment]
Thanks @travisbrown! 2.1x still looks pretty impressive to me!
